### PR TITLE
fix: remove deprecated juggler-v3 and juggler-v4 deps folder and update test cases

### PR DESCRIPTION
**Pull request by samarpanB**
Signed-off-by: Samarpan Bhattacharya <this.is.samy@gmail.com>

Remove deprecated multiple juggler deps test cases as we now dont support nodejs v12 and juggler v3 versions
Added some more test cases for createAll to verify #530 

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by samarpanB** [comment]
Test cases will work after https://github.com/loopbackio/loopback-datasource-juggler/pull/2027 is released.

**Review by dhmlau — APPROVED** [review]
LGTM. It makes sense to drop juggler-v3. Looks like this will be another breaking change.

**Comment by samarpanB** [comment]
> LGTM. It makes sense to drop juggler-v3. Looks like this will be another breaking change.

We already made this breaking change last time. This was just left over.

**Comment by dhmlau** [comment]
Actually I meant dropping juggler 3, looks like we've done it in https://github.com/loopbackio/loopback-connector-postgresql/commit/4b8ce8a6157ce7b429679d93ab2b6a0907cee95b which is part of the 6.0.0 release. Removing the breaking-change label. Sorry about that.

**Pull request merged**
